version: "3"
networks:
    wordpressdev1-network:
        driver: bridge

services:
    mysql:
        image: mysql:5.7
        container_name: wordpressdev-mysql
        tty: true
        ports:
            - "4208:3306"
        volumes:
            - "./var/libclea/mysql/:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: user
            MYSQL_DATABASE: user
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        networks:
            - wordpressdev1-network

    server:
        image: wordpress:latest
        container_name: wordpressdev-server
        ports:
            - "4282:80"
        volumes:
            - "./var/www/html/:/var/www/html"
        environment:
            WORDPRESS_DB_USER: user
            WORDPRESS_DB_PASSWORD: user
            WORDPRESS_DB_NAME: user
            WORDPRESS_DB_HOST: wordpressdev-mysql
        depends_on:
            - mysql
        networks:
            -  wordpressdev1-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ds-phpmyadmin
        ports:
            - "4283:80"
        environment:
            PMA_HOST: wordpressdev-server
            MYSQL_ROOT_PASSWORD: user
        depends_on:
            - mysql
        networks:
            -  wordpressdev1-network